### ISSUE TITLE
Document environment variables in the README

### ISSUE THREAD

**Issue by bobsilverberg** [davehunt/hubot-bugzilla#1]
It might be worth documenting the `HUBOT_BUGZILLA_URL` and `HUBOT_BUGZILLA_IGNORE_USERS` environment variables in the README so a new user will know what they are for, and that one is required.

**Comment by davehunt** [comment]
I followed convention here by documenting them in the coffeescript and linking to that from the README. If you still think we should add it to the README then please feel free to submit a patch.
